apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cicd-pipeline
  namespace: e27db1-tools
spec:
  params:
    - name: git-url
    - name: git-revision
      default: develop
    - name: git-short-sha
    - name: image-registry
      default: image-registry.openshift-image-registry.svc:5000/e27db1-tools
    - name: image-tag
      default: develop
    - name: release_name
      default: dev
    - name: release_namespace
      default: e27db1-test
    - name: release_version
      default: "v0.1.0"
    - name: values_file
      default: deploy/test_values.yaml
  workspaces:
    - name: source
    - name: dockerconfig
  tasks:
    - name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: jps-pidp
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: ClusterTask
        name: git-clone-v0-22-0
    - name: build-frontend
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
      taskRef:
        kind: Task
        name: build-frontend
      params:
        - name: PATH_CONTEXT
          value: jps-pidp/workspace/
      runAfter: 
        - git-clone
    - name: build-frontend-image
      workspaces:
        - name: source
          workspace: source
      taskRef:
        kind: Task
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)/pidp-frontend:$(params.image-tag)
        - name: CONTEXT
          value: jps-pidp/workspace/
        - name: DOCKERFILE
          value: jps-pidp/workspace/Dockerfile
        - name: EXTRA_ARGS
          value: 
            - --skip-tls-verify
      runAfter: 
        - build-frontend
    - name: build-webapi
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
      taskRef:
        kind: Task
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)/pidp-webapi:$(params.image-tag)
        - name: CONTEXT
          value: jps-pidp/backend/webapi/
        - name: DOCKERFILE
          value: jps-pidp/backend/webapi/Dockerfile
        - name: EXTRA_ARGS
          value: 
            - --skip-tls-verify
      runAfter: 
        - git-clone
    - name: build-edt-service
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
      taskRef:
        kind: Task
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)/edt-service:$(params.image-tag)
        - name: CONTEXT
          value: jps-pidp/backend/service.edt/
        - name: DOCKERFILE
          value: jps-pidp/backend/service.edt/Dockerfile
        - name: EXTRA_ARGS
          value: 
            - --skip-tls-verify
      runAfter: 
        - git-clone    
    - name: build-plr-intake
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
      taskRef:
        kind: Task
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-registry)/pidp-plr-intake:$(params.image-tag)
        - name: CONTEXT
          value: jps-pidp/backend/services.plr-intake/
        - name: DOCKERFILE
          value: jps-pidp/backend/services.plr-intake/Dockerfile
        - name: EXTRA_ARGS
          value: 
            - --skip-tls-verify
      runAfter: 
        - git-clone
    - name: install-upgrade
      workspaces:
        - name: source
          workspace: source
      params:
      - name: charts_dir
        value: ./jps-pidp/charts/pidp
      - name: release_version
        value: $(params.release_version)
      - name: release_name
        value: $(params.release_name)
      - name: release_namespace
        value: $(params.release_namespace)
      - name: overwrite_values
        value: global.image.tag=$(params.image-tag),global.commit_sha=$(params.git-short-sha)
      - name: values_file
        value: jps-pidp/$(params.values_file)
      taskRef:
        name: helm-upgrade-from-source
      runAfter: 
        - git-clone
        - build-plr-intake
        - build-frontend-image
        - build-webapi
        - build-edt-service