apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
    service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.application_name }}-postgresql",
      "kind": "Service"}]'
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-https-secret
  labels:
    application: {{ .Values.application_name }}
    rhsso: 7.6.0.GA
    template: sso76-ocp4-x509-postgresql-persistent
  name: {{ include "sso.fullname" . }}-https
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    {{- include "sso.selectorLabels" . | nindent 4 }}
#---
#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    description: The database server's port.
#  labels:
#    application: {{ .Values.application_name }}-db
#    rhsso: 7.6.0.GA
#    template: sso76-ocp4-x509-postgresql-persistent
#  name: {{ include "sso.fullname" . }}-postgresql
#spec:
#  ports:
#    - port: 5432
#      targetPort: 5432
#  selector:
#    {{- include "sso.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-jgroups-secret
  labels:
    application: {{ .Values.application_name }}
    rhsso: 7.6.0.GA
    template: sso76-ocp4-x509-postgresql-persistent
  name: {{ include "sso.fullname" . }}-ping
spec:
  clusterIP: None
  ports:
    - name: ping
      port: 8888
  publishNotReadyAddresses: true
  selector:
    {{- include "sso.selectorLabels" . | nindent 4 }}
