apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dems-notification-ack
  labels:
    strimzi.io/cluster: pidp-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dems-access-request
  labels:
    strimzi.io/cluster: pidp-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dems-access-request
  labels:
    strimzi.io/cluster: pidp-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824