{{- $separator :=  ternary "-" "." (regexMatch "(?:\\..*?){4}" .Values.global.vanityURL) -}}
{{- $domain := .Values.global.vanityURL -}}
{{- $fullName := include "frontend.fullname" . -}}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
{{ $isProd := contains "prod" $ocEnv }}
#
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  environment.json: |-
    {
      "environmentName": "{{ .Values.settings.environmentName }}",
      "apiEndpoint": "https://{{ $domain }}/api/v1",
      "applicationUrl": "https://{{ $domain }}",
      "keycloakConfig": {
        "config": {
          "url": "{{ .Values.settings.keycloak.url }}",
          "realm": "{{ .Values.settings.keycloak.realm }}",
          "clientId": "{{ .Values.settings.keycloak.clientId }}"
        },
        "initOptions": {
          "onLoad": "check-sso"
        }
      }
    }
