apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-push
  namespace: e27db1-tools
spec:
  namespaceSelector: {}
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
            - name: ""
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 250m
                  memory: 64Mi
            serviceAccountName: pipeline
  serviceAccountName: ""
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: github-push-binding
    - name: release-namespace
      value: e27db1-dev
    - name: release-name
      value: dev
    - name: values-file
      value: deploy/dev_values.yaml
    name: github-dev
    interceptors:
    - cel:
        filter: >-
          header.match('X-GitHub-Event', 'push') &&
          body.repository.full_name == 'sookeke/jps-pidp' &&
          body.ref == 'refs/heads/develop'
        overlays:
        - key: truncated_sha
          expression: "body.head_commit.id.truncate(7)"
        - key: branch_name
          expression: "body.ref.replace('refs/heads/', '')"
    template:
      ref: github-push-trigger-template
  - bindings:
    - kind: TriggerBinding
      ref: github-push-binding
    - name: release-namespace
      value: e27db1-test
    - name: release-name
      value: test
    - name: values-file
      value: deploy/test_values.yaml
    name: github-test
    interceptors:
    - cel:
        filter: >-
          header.match('X-GitHub-Event', 'push') &&
          body.repository.full_name == 'sookeke/jps-pidp' &&
          body.ref == 'refs/heads/test'
        overlays:
        - key: truncated_sha
          expression: "body.head_commit.id.truncate(7)"
        - key: branch_name
          expression: "body.ref.replace('refs/heads/', '')"
    template:
      ref: github-push-trigger-template
  - bindings:
    - kind: TriggerBinding
      ref: github-push-binding
    - name: release-namespace
      value: e27db1-test
    - name: release-name
      value: demo
    - name: values-file
      value: deploy/demo_values.yaml
    name: github-demo
    interceptors:
    - cel:
        filter: >-
          header.match('X-GitHub-Event', 'push') &&
          body.repository.full_name == 'sookeke/jps-pidp' &&
          body.ref == 'refs/heads/main'
        overlays:
        - key: truncated_sha
          expression: "body.head_commit.id.truncate(7)"
        - key: branch_name
          expression: "body.ref.replace('refs/heads/', '')"
    template:
      ref: github-push-trigger-template
  - bindings:
    - kind: TriggerBinding
      ref: github-push-binding
    - name: release-namespace
      value: e27db1-prod
    - name: release-name
      value: prod
    - name: values-file
      value: deploy/prod_values.yaml
    name: github-prod
    interceptors:
    - cel:
        filter: >-
          header.match('X-GitHub-Event', 'push') &&
          body.repository.full_name == 'sookeke/jps-pidp' &&
          body.ref == 'refs/heads/main'
        overlays:
        - key: truncated_sha
          expression: "body.head_commit.id.truncate(7)"
        - key: branch_name
          expression: "body.ref.replace('refs/heads/', '')"
    template:
      ref: github-push-trigger-template
