{{- if .Values.kafka.kafkaui.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "pidp-kafka.fullname" . }}-kafka-ui
  labels:
    {{- include "pidp-kafka.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pidp-kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pidp-kafka.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: kafka-ui
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          securityContext: {}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: {{ include "pidp-kafka.fullname" . }}-ui-config
          image: 'docker.io/provectuslabs/kafka-ui:v0.4.0'
          volumeMounts:
            - name: truststore
              mountPath: "/opt/kafka/certificates"
              readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kafka-ui
      serviceAccount: kafka-ui
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: truststore
          secret:
            secretName: {{ include "pidp-kafka.fullname" . }}-cluster-cluster-ca-cert
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end}}
