apiVersion: v1
kind: Service
metadata:
  name: {{ include "pidp-kafka.fullname" . }}
  labels:
    {{- include "pidp-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pidp-kafka.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pidp-kafka.fullname" . }}-kafka-ui
  labels:
    {{- include "pidp-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pidp-kafka.selectorLabels" . | nindent 4 }}
