{{- if .Values.migrations.enabled }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "plr-intake.fullname" . }}-migrations
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "10"
  labels:
    {{- include "plr-intake.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        command: ['./efbundle', '--connection', '$(ConnectionStrings__PlrDatabase)']
        env:
          - name: DB_HOST
            value: pidp-postgresql
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pidp-postgresql
                key: database-password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: pidp-postgresql
                key: database-user
          - name: POSTGRESQL_DATABASE
            {{- if $isPR }}
            value: pidp_{{ $drn }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: pidp-postgresql
                key: database-name
            {{- end }}
          - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
            value: /tmp
          - name: ConnectionStrings__PlrDatabase
            valueFrom:
                configMapKeyRef:
                  name: pidp-plr-database
                  key: CONNECTION_STRINGS_PLR
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
